### PR TITLE
updating dependencies + making input not disappear on failure

### PR DESCRIPTION
**Pull request by soupi**
Hi, there are two commits to this pull request:

- the first will update the dependencies so the project will compiler
- the second will make the input text not disappear on failure

Thanks

### CODE REVIEW

**Comment by cdparks** [comment]
Hey, thanks for the PR.

I like the change to not delete input, but this don't build with my version of `psc`. What version are you using? I have version 0.7.4.1 right now:

```bash
psc --version
0.7.4.1
```

Are you using latest?

**Comment by soupi** [comment]
Yes, I am using 8.0.0. the latest. if you like the change I guess you can just make the change in your version instead and close this PR :)

**Comment by cdparks** [comment]
I just made a release for the old version, so if you update your PR, I'll merge it, test it locally on latest, and make a new release.

**Comment by cdparks** [comment]
Ok, great, this builds with 0.7.6.1 and 0.8.0-rc1. Thanks again!

**Comment by soupi** [comment]
great. thanks :)

**Comment by soupi** [comment]
oh, actually, it looks like the gh-pages branch broke.

**Comment by cdparks** [comment]
Gah, good catch. I somehow managed to compile a version that was missing the `Prelude` code. I pushed an update, and the github page should update soon. It's still showing the cached version now though.

**Pull request merged**
